const PDFDocument=require("pdfkit")

const fs=require("fs")

const path=require("path")

const supabase=require("../config/supabase")

exports.generateReport=async(data)=>{

const reportsDir=path.join(__dirname,"../reports")

if(!fs.existsSync(reportsDir)){

fs.mkdirSync(reportsDir)

}

const fileName=`report-${Date.now()}.pdf`

const filePath=path.join(reportsDir,fileName)

const doc=new PDFDocument({

size:"A4",

margin:50

})

const stream=fs.createWriteStream(filePath)

doc.pipe(stream)



// HEADER

doc

.rect(0,0,595,90)

.fill("#2563eb")



doc

.fillColor("white")

.fontSize(26)

.font("Helvetica-Bold")

.text(

"INTERVIEW AI",

50,

25

)



doc

.fontSize(12)

.font("Helvetica")

.text(

"AI Mock Interview Report",

50,

60

)



// START BODY

doc.y=120



doc

.fillColor("black")

.fontSize(22)

.font("Helvetica-Bold")

.text(

data.role,

{

align:"center"

}

)



doc.moveDown()



doc

.fontSize(16)

.font("Helvetica-Bold")

.text(

"OVERALL SCORE",

{

align:"center"

}

)



doc

.fillColor("#2563eb")

.fontSize(40)

.text(

`${data.overallScore}%`,

{

align:"center"

}

)



doc.moveDown()



doc

.fillColor("black")

.fontSize(18)

.font("Helvetica-Bold")

.text(

"PERFORMANCE SUMMARY"

)



doc.moveDown()



const metrics=[

["Technical",data.technicalScore],

["Communication",data.communicationScore],

["Confidence",data.confidenceScore],

["Fluency",data.fluencyScore],

["Pronunciation",data.pronunciationScore]

]



metrics.forEach(item=>{

doc

.fontSize(13)

.font("Helvetica")

.text(

`${item[0]} : ${item[1]}%`

)

})



doc.moveDown()



doc

.fontSize(18)

.font("Helvetica-Bold")

.text(

"TOP AI INSIGHTS"

)



doc.moveDown()



const insights=[]



if(data.technicalScore<70){

insights.push(

"Improve technical concepts"

)

}



if(data.communicationScore<70){

insights.push(

"Improve communication"

)

}



if(data.confidenceScore<70){

insights.push(

"Increase confidence"

)

}



if(data.fluencyScore<70){

insights.push(

"Reduce filler words"

)

}



if(insights.length===0){

insights.push(

"Strong overall performance"

)

}



insights.forEach(item=>{

doc

.fontSize(13)

.font("Helvetica")

.text(

`✓ ${item}`

)

})



doc.moveDown()



doc

.fontSize(18)

.font("Helvetica-Bold")

.text(

"RECRUITER VERDICT"

)



doc.moveDown()



let verdict=""


if(data.overallScore>=85){

verdict="Excellent candidate. Ready for interviews."

}

else if(data.overallScore>=70){

verdict="Good candidate with minor improvements."

}

else if(data.overallScore>=50){

verdict="Needs additional preparation."

}

else{

verdict="Significant preparation required."

}



doc

.fontSize(13)

.font("Helvetica")

.text(

verdict

)



doc.moveDown()



doc

.fontSize(18)

.font("Helvetica-Bold")

.text(

"NEXT STEPS"

)



doc.moveDown()



doc

.fontSize(13)

.font("Helvetica")

.text(

"1. Revise weak topics"

)



doc.text(

"2. Practice mock interviews"

)



doc.text(

"3. Record your answers"

)



doc.moveDown(3)



doc

.fontSize(10)

.fillColor("gray")

.text(

"Generated by InterviewAI",

{

align:"center"

}

)



doc.end()



return new Promise(

(resolve,reject)=>{

stream.on(

"finish",

async()=>{

try{

const pdfBuffer=

fs.readFileSync(

filePath

)

console.log("Uploading report to Supabase...")

const {

data:uploadData,

error:uploadError

}=await supabase

.storage

.from(

"report-files"

)

.upload(

fileName,

pdfBuffer,

{

contentType:"application/pdf"

}

)

console.log(

"UPLOAD DATA:",

uploadData

)

console.log(

"UPLOAD ERROR:",

uploadError

)

if(uploadError){

throw uploadError

}

const {

data:publicUrlData

}=supabase

.storage

.from(

"report-files"

)

.getPublicUrl(

fileName

)

fs.unlinkSync(

filePath

)

resolve(

publicUrlData.publicUrl

)

}

catch(err){

reject(err)

}

}

)

stream.on(

"error",

reject

)

}

)

}