const PDFDocument=require("pdfkit")

const fs=require("fs")

const path=require("path")

const supabase=require("../config/supabase")

exports.generateResumeReport=async(data)=>{

const reportsDir=path.join(__dirname,"../reports")

if(!fs.existsSync(reportsDir)){

fs.mkdirSync(reportsDir)

}

const fileName=`resume-${Date.now()}.pdf`

const filePath=path.join(reportsDir,fileName)

const doc=new PDFDocument({

margin:40,

size:"A4"

})

const stream=fs.createWriteStream(filePath)

doc.pipe(stream)



// -----------------------------

// DATA CLEANING

// -----------------------------

const ats=data.atsScore || 0

const skills=(data.skills || []).slice(0,8)

const suggestions=(data.suggestions || []).slice(0,5)



let verdict=""



if(ats>=85){

verdict="Excellent resume. Recruiter ready."

}

else if(ats>=70){

verdict="Strong resume with a few improvements needed."

}

else if(ats>=50){

verdict="Good foundation but needs optimization."

}

else{

verdict="Resume needs major improvements."

}



// -----------------------------

// HEADER

// -----------------------------

doc

.rect(0,0,595,95)

.fill("#2563eb")



doc

.fillColor("white")

.fontSize(28)

.font("Helvetica-Bold")

.text(

"INTERVIEW AI",

45,

25

)



doc

.fontSize(13)

.font("Helvetica")

.text(

"AI Resume Analysis Report",

45,

60

)



// -----------------------------

// ATS CARD

// -----------------------------

doc

.roundedRect(

45,

130,

500,

85,

15

)

.fillAndStroke(

"#eff6ff",

"#2563eb"

)



doc

.fillColor("black")

.fontSize(16)

.font("Helvetica-Bold")

.text(

"ATS SCORE",

75,

160

)



doc

.fillColor("#2563eb")

.fontSize(34)

.font("Helvetica-Bold")

.text(

`${ats}%`,

430,

150

)



doc

.fillColor("gray")

.fontSize(12)

.text(

ats>=80

?"Excellent"

:ats>=70

?"Good"

:ats>=50

?"Average"

:"Needs Work",

445,

190

)





// ======================================

// RESET POSITION

// ======================================

doc.x=45

doc.y=250



// --------------------------------------

// AI FEEDBACK

// --------------------------------------

doc

.fillColor("black")

.fontSize(20)

.font("Helvetica-Bold")

.text(

"AI FEEDBACK"

)



doc.moveDown(0.7)



suggestions.forEach((item)=>{

doc

.fontSize(12)

.font("Helvetica")

.text(

`• ${item}`,

{

width:500,

align:"left"

}

)

})



doc.moveDown(1)



// --------------------------------------

// KEY SKILLS

// --------------------------------------

doc

.fontSize(20)

.font("Helvetica-Bold")

.text(

"KEY SKILLS"

)



doc.moveDown(0.5)



doc

.fontSize(13)

.font("Helvetica")

.text(

skills.join("   •   "),

{

width:500,

align:"left"

}

)



doc.moveDown(1)



// --------------------------------------

// RECRUITER VERDICT

// --------------------------------------

doc

.fontSize(20)

.font("Helvetica-Bold")

.text(

"RECRUITER VERDICT"

)



doc.moveDown(0.5)



doc

.fontSize(13)

.font("Helvetica")

.text(

verdict,

{

width:500,

align:"left"

}

)



doc.moveDown(1.5)



// --------------------------------------

// ACTION PLAN

// --------------------------------------

doc

.fontSize(20)

.font("Helvetica-Bold")

.text(

"3 STEP ACTION PLAN"

)



doc.moveDown(0.5)



doc

.fontSize(13)

.font("Helvetica")

.text(

"1. Customize resume for every job application"

)



doc.text(

"2. Add measurable achievements"

)



doc.text(

"3. Add professional links (LinkedIn/GitHub)"

)



// --------------------------------------

// FOOTER

// --------------------------------------

doc.moveDown(3)



doc

.fontSize(10)

.fillColor("gray")

.text(

"Generated by InterviewAI",

{

align:"center"

}

)



doc.end()



return new Promise((resolve,reject)=>{

stream.on(

"finish",

async()=>{

try{

const pdfBuffer=

fs.readFileSync(filePath)

const {

error

}=await supabase

.storage

.from(

"report-files"

)

.upload(

fileName,

pdfBuffer,

{

contentType:

"application/pdf"

}

)

if(error){

throw error

}

const {

data

}=supabase

.storage

.from(

"report-files"

)

.getPublicUrl(

fileName

)

fs.unlinkSync(

filePath

)

resolve(

data.publicUrl

)

}

catch(err){

reject(err)

}

}

)

stream.on(

"error",

reject

)

})

}